---
markdown: kramdown
highlighter: pygments
permalink: pretty

title: "Harmonic Labyrinth"
tagline: "Easy to enter, difficult to escape"

description: "Eugênio's Blog"

url: https://eug.github.io

baseurl: "/"

author:
  name: Eugênio
  url: "https://github.com/eug"

cover: "/assets/images/escher_labyrinth.jpg"

paginate: 4

version: 2.1.0

mathjax: true

disqus:
  shortname: "eug-github-io"

analytics:
  id: "UA-88666454-1"

social:
  email: eugfcl@gmail.com
  github: https://github.com/eug
  linkedin: https://br.linkedin.com/in/eugfc
  twitter: https://twitter.com/eugf_

gems:
- jekyll-admin
- jekyll-paginate
- jekyll-gist