---
markdown: redcarpet
highlighter: pygments

permalink: pretty

title: "Harmonic Labyrinth"
tagline: "Easy to enter, difficult to escape"
#Reporting lovely stories between me and a text-editor

description: "Eugênio's Blog"

url: https://eug.github.io

baseurl: "/"

author:
  name: Eugênio
  url: https://twitter.com/eugf_



cover: "/assets/images/escher_labyrinth.jpg"

paginate: 4

version: 2.1.0

mathjax: true

disqus: eugfcl

analytics:
  id: "UA-88666454-1"


social:
  email: eugfcl@gmail.com
  github: https://github.com/eug
  linkedin: https://br.linkedin.com/in/eugfc
  twitter: https://twitter.com/eugf_

github:
  repo: 

gems:
- jekyll-admin
- jekyll-paginate
- jekyll-gist