name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Specify your Python version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build static site
        run: python main.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # If you are deploying to a custom domain, add it here
          # cname: your.custom.domain.com
          #
          # If you are deploying to a user or organization page (e.g., <username>.github.io),
          # the publish_branch is typically 'main' or 'master' and publish_dir is './output' (or your build output).
          # For a project page (e.g., <username>.github.io/<repository-name>),
          # the publish_branch is typically 'gh-pages'.
          publish_branch: gh-pages  # Deploy to gh-pages branch
          force_orphan: true    # Ensure clean deployment
          # user_name: 'github-actions[bot]' # Optional: Custom committer name
          # user_email: 'github-actions[bot]@users.noreply.github.com' # Optional: Custom committer email
          # commit_message: 'Deploy to GitHub Pages' # Optional: Custom commit message 